FROM openjdk:8-jre

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \
  && apt -y install tzdata \
  && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ADD seatunnel-dist/target/apache-seatunnel-*-SNAPSHOT-bin.tar.gz /seatunnel/apache-seatunnel

ENTRYPOINT ["/bin/sh","/seatunnel/apache-seatunnel/bin/seatunnel-cluster.sh","-d"]